name: Checkov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Checkov
      run: |
        sudo apt-get update && sudo apt-get install -y python3-pip
        pip3 install checkov
    - name: Run Checkov
      run: |
        checkov -d . -o cyclonedx_json
